# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

# Pods for ShopAppLiverpool
def liverpoolPod
  # Image managers
  pod 'Kingfisher' # Downloading and caching images
end

target 'ShopAppLiverpool' do
  liverpoolPod
end

